# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - tree

script:
  - ./autogen.sh
  - ./configure --prefix=/tmp
  - make clean
  - make V=1 -j5
  - make install-strip
  - tree /tmp
  - ls -l /tmp/bin/logit
  - /tmp/bin/logit -h
  - ldd /tmp/bin/logit
